name: myportfolio
description: "Mohab Gamal's Flutter Developer Portfolio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dynamic_color: null
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_form_builder: null
  flutter_hooks: ^0.20.0
  flutter_markdown: ^0.6.18
  flutter_masonry_view: ^0.0.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.8.0
  form_validator: null
  google_fonts: null
  masonry_grid: ^1.0.0
  provider: ^6.1.1
  rive: ^0.13.20
  url_launcher: ^6.1.11
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/icons/
    # - assets/svgs/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: SpaceGrotesk
  #     fonts:
  #       - asset: assets/fonts/SpaceGrotesk-Regular.ttf
  #       - asset: assets/fonts/SpaceGrotesk-Bold.ttf
  #         weight: 700
